### ISSUE TITLE
Modules seems to be finalizing before socket terminated

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/socketio#20]
Or something like that...

See the following error from `nio.err`

```
Exception in thread SocketIOWebSocketClient:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/nio_versions/1.4.1/lib/python3.4/site-packages/ws4py/websocket.py", line 430, in run
    self.terminate()
  File "/home/ubuntu/nio_versions/1.4.1/lib/python3.4/site-packages/ws4py/websocket.py", line 327, in terminate
    self.closed(1006, "Going away")
  File "/home/ubuntu/nio-projects/mobile_demo/blocks/socketio/client_1.py", line 32, in closed
    self.handle_disconnect()
  File "/home/ubuntu/nio-projects/mobile_demo/blocks/socketio/client_1.py", line 36, in handle_disconnect
    self._restart_handler()
  File "/home/ubuntu/nio-projects/mobile_demo/blocks/socketio/socketio_base.py", line 79, in handle_reconnect
    repeatable=False)
  File "/var/lib/jenkins/jobs/nio/workspace/deployment/dist/nio-1.4.1-py3-none-any.whl-ext/nio/modules/scheduler/__init__.py", line 78, in __init__
  File "/var/lib/jenkins/jobs/nio/workspace/deployment/dist/nio-1.4.1-py3-none-any.whl-ext/nio/modules/scheduler/__init__.py", line 34, in schedule_task
NotImplementedError
```

**Comment by f1401martin** [comment]
This could be just a module ordering issue

**Comment by mattdodge** [comment]
Haven't seen this for quite some time, seems to have been a nio issue that was fixed already. Closing
